# Generated by Django 3.1.4 on 2020-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='cont_status',
            field=models.CharField(choices=[('Loaded', 'Loaded'), ('Arrived', 'Arrived')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Collected', 'Collected'), ('Loaded', 'Loaded'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
