# Generated by Django 3.1.4 on 2020-12-28 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_auto_20201227_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='cont_status',
            field=models.CharField(blank=True, choices=[('Loaded', 'Loaded'), ('Arrived', 'Arrived')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.container'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Collected', 'Collected'), ('Loaded', 'Loaded'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
