# Generated by Django 3.1.4 on 2020-12-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_auto_20201229_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='select',
            field=models.BooleanField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.container'),
        ),
    ]
