# Generated by Django 3.1.4 on 2020-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_auto_20201229_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='select',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
